/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteSlugRouteImport } from './routes/invite.$slug'
import { Route as InviteSlugIndexRouteImport } from './routes/invite.$slug.index'
import { Route as InviteSlugGuestIdRouteImport } from './routes/invite.$slug.$guestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteSlugRoute = InviteSlugRouteImport.update({
  id: '/invite/$slug',
  path: '/invite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteSlugIndexRoute = InviteSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InviteSlugRoute,
} as any)
const InviteSlugGuestIdRoute = InviteSlugGuestIdRouteImport.update({
  id: '/$guestId',
  path: '/$guestId',
  getParentRoute: () => InviteSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite/$slug': typeof InviteSlugRouteWithChildren
  '/invite/$slug/$guestId': typeof InviteSlugGuestIdRoute
  '/invite/$slug/': typeof InviteSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$slug/$guestId': typeof InviteSlugGuestIdRoute
  '/invite/$slug': typeof InviteSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite/$slug': typeof InviteSlugRouteWithChildren
  '/invite/$slug/$guestId': typeof InviteSlugGuestIdRoute
  '/invite/$slug/': typeof InviteSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invite/$slug' | '/invite/$slug/$guestId' | '/invite/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invite/$slug/$guestId' | '/invite/$slug'
  id:
    | '__root__'
    | '/'
    | '/invite/$slug'
    | '/invite/$slug/$guestId'
    | '/invite/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteSlugRoute: typeof InviteSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$slug': {
      id: '/invite/$slug'
      path: '/invite/$slug'
      fullPath: '/invite/$slug'
      preLoaderRoute: typeof InviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$slug/': {
      id: '/invite/$slug/'
      path: '/'
      fullPath: '/invite/$slug/'
      preLoaderRoute: typeof InviteSlugIndexRouteImport
      parentRoute: typeof InviteSlugRoute
    }
    '/invite/$slug/$guestId': {
      id: '/invite/$slug/$guestId'
      path: '/$guestId'
      fullPath: '/invite/$slug/$guestId'
      preLoaderRoute: typeof InviteSlugGuestIdRouteImport
      parentRoute: typeof InviteSlugRoute
    }
  }
}

interface InviteSlugRouteChildren {
  InviteSlugGuestIdRoute: typeof InviteSlugGuestIdRoute
  InviteSlugIndexRoute: typeof InviteSlugIndexRoute
}

const InviteSlugRouteChildren: InviteSlugRouteChildren = {
  InviteSlugGuestIdRoute: InviteSlugGuestIdRoute,
  InviteSlugIndexRoute: InviteSlugIndexRoute,
}

const InviteSlugRouteWithChildren = InviteSlugRoute._addFileChildren(
  InviteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteSlugRoute: InviteSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
