/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteSlugRouteImport } from './routes/invite.$slug'
import { Route as InviteSlugIndexRouteImport } from './routes/invite.$slug.index'
import { Route as InviteSlugGuestIdRouteImport } from './routes/invite.$slug.$guestId'
import { Route as BuilderIndexRouteImport } from './routes/builder.index'
import { Route as BuilderInvitationIdRouteImport } from './routes/builder.$invitationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteSlugRoute = InviteSlugRouteImport.update({
  id: '/invite/$slug',
  path: '/invite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteSlugIndexRoute = InviteSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InviteSlugRoute,
} as any)
const InviteSlugGuestIdRoute = InviteSlugGuestIdRouteImport.update({
  id: '/$guestId',
  path: '/$guestId',
  getParentRoute: () => InviteSlugRoute,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/builder/',
  path: '/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderInvitationIdRoute = BuilderInvitationIdRouteImport.update({
  id: '/builder/$invitationId',
  path: '/builder/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite/$slug': typeof InviteSlugRouteWithChildren
  '/invite/$slug/$guestId': typeof InviteSlugGuestIdRoute
  '/invite/$slug/': typeof InviteSlugIndexRoute
  '/builder/$invitationId': typeof BuilderInvitationIdRoute
  '/builder/': typeof BuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$slug/$guestId': typeof InviteSlugGuestIdRoute
  '/invite/$slug': typeof InviteSlugIndexRoute
  '/builder/$invitationId': typeof BuilderInvitationIdRoute
  '/builder': typeof BuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite/$slug': typeof InviteSlugRouteWithChildren
  '/invite/$slug/$guestId': typeof InviteSlugGuestIdRoute
  '/invite/$slug/': typeof InviteSlugIndexRoute
  '/builder/$invitationId': typeof BuilderInvitationIdRoute
  '/builder/': typeof BuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite/$slug'
    | '/invite/$slug/$guestId'
    | '/invite/$slug/'
    | '/builder/$invitationId'
    | '/builder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$slug/$guestId'
    | '/invite/$slug'
    | '/builder/$invitationId'
    | '/builder'
  id:
    | '__root__'
    | '/'
    | '/invite/$slug'
    | '/invite/$slug/$guestId'
    | '/invite/$slug/'
    | '/builder/$invitationId'
    | '/builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteSlugRoute: typeof InviteSlugRouteWithChildren
  BuilderInvitationIdRoute: typeof BuilderInvitationIdRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$slug': {
      id: '/invite/$slug'
      path: '/invite/$slug'
      fullPath: '/invite/$slug'
      preLoaderRoute: typeof InviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$slug/': {
      id: '/invite/$slug/'
      path: '/'
      fullPath: '/invite/$slug/'
      preLoaderRoute: typeof InviteSlugIndexRouteImport
      parentRoute: typeof InviteSlugRoute
    }
    '/invite/$slug/$guestId': {
      id: '/invite/$slug/$guestId'
      path: '/$guestId'
      fullPath: '/invite/$slug/$guestId'
      preLoaderRoute: typeof InviteSlugGuestIdRouteImport
      parentRoute: typeof InviteSlugRoute
    }
    '/builder/$invitationId': {
      id: '/builder/$invitationId'
      path: '/builder/$invitationId'
      fullPath: '/builder/$invitationId'
      preLoaderRoute: typeof BuilderInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/builder'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InviteSlugRouteChildren {
  InviteSlugGuestIdRoute: typeof InviteSlugGuestIdRoute
  InviteSlugIndexRoute: typeof InviteSlugIndexRoute
}

const InviteSlugRouteChildren: InviteSlugRouteChildren = {
  InviteSlugGuestIdRoute: InviteSlugGuestIdRoute,
  InviteSlugIndexRoute: InviteSlugIndexRoute,
}

const InviteSlugRouteWithChildren = InviteSlugRoute._addFileChildren(
  InviteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteSlugRoute: InviteSlugRouteWithChildren,
  BuilderInvitationIdRoute: BuilderInvitationIdRoute,
  BuilderIndexRoute: BuilderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
